spring:
  application:
    name: Task API

  datasource:
    url: "jdbc:postgresql://localhost:5432/task-tracker-db"
    username: "postgres"
    password: "123"
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
    
    

